name: Output Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Create Version
        id: step2
        run: echo "test=1.0.0" >> $GITHUB_OUTPUT

      - name: Use Version
        run: echo "${{ steps.step2.outputs.test }}"

  
